import { AlertTriangle, Bell, CalendarCheck, CheckCircle2, ChevronRight, HeartHandshake, Phone, ShieldCheck, UserRound } from "lucide-react";
import RoleSwitcher from "../components/RoleSwitcher";
import { useEffect, useState } from "react";
import { getCaretakerWorkspace } from "../api/client";

export default function CaretakerDashboard() {
  const [backendConnected, setBackendConnected] = useState(false);
  useEffect(() => {
    getCaretakerWorkspace().then(() => setBackendConnected(true)).catch(() => setBackendConnected(false));
  }, []);
  return <div className="wellbeing-page caretaker-page"><header className="wellbeing-header"><div className="wellbeing-brand"><div className="wellbeing-brand-mark caretaker-mark"><HeartHandshake /></div><div><strong>NeuroTrace</strong><span>Caretaker space</span></div></div><RoleSwitcher role="caretaker" /></header><main className="wellbeing-content"><section className="wellbeing-welcome"><div><span className="wellbeing-eyebrow">CARETAKER DASHBOARD</span><h1>Supporting Margaret, together.</h1><p>Stay close to the daily details that help care feel calm and consistent.</p></div><div className="connected-chip"><span /> Patient connected</div></section><section className="caretaker-grid"><article className="wellbeing-card medication-card"><div className="card-heading"><div><span className="wellbeing-eyebrow">MEDICATION FOLLOW-UP</span><h2>Today's medicines</h2></div><Bell /></div><div className="medication-row"><div className="medication-time">08:00</div><div><strong>Morning medication</strong><p>Done at 08:14</p></div><CheckCircle2 className="done-icon" /></div><div className="medication-row pending"><div className="medication-time">20:00</div><div><strong>Evening medication</strong><p>Reminder scheduled</p></div><button className="small-action">Mark follow-up</button></div></article><article className="wellbeing-card safety-card"><div className="card-heading"><div><span className="wellbeing-eyebrow">PRECAUTIONS &amp; SAFETY</span><h2>Safety check</h2></div><ShieldCheck /></div><div className="safety-status"><ShieldCheck /><div><strong>All clear today</strong><p>No new safety concerns reported.</p></div></div><button className="text-action">Review safety guidance <ChevronRight /></button></article><article className="wellbeing-card contact-card"><div className="card-heading"><div><span className="wellbeing-eyebrow">DOCTOR CONTACT</span><h2>Care team</h2></div><UserRound /></div><div className="doctor-person"><div className="avatar">DR</div><div><strong>Dr. Elena Marquez</strong><p>Neurology care team</p></div><button className="circle-action" aria-label="Call doctor"><Phone /></button></div><button className="wellbeing-button light">Message care team</button></article><article className="wellbeing-card emergency-card"><div className="card-heading"><div><span className="wellbeing-eyebrow">SUPPORT / EMERGENCY CONTACTS</span><h2>Help when you need it</h2></div><AlertTriangle /></div><p>Keep trusted contacts close and know who to call in an urgent situation.</p><div className="emergency-actions"><button className="emergency-button"><Phone /> Emergency services <strong>112</strong></button><button className="support-button"><Phone /> Family contact <strong>Call</strong></button></div></article></section><section className="care-note"><CalendarCheck /><div><strong>Next care review</strong><span>Thursday, October 3 at 10:00 with Dr. Marquez</span></div></section></main></div>;
}
